//! The record of what `data/` holds and where it came from.
//!
//! The point of the manifest is that a compressed copy of somebody else's file
//! is otherwise untraceable. Recording the checksum of the *plaintext* rather
//! than of the compressed file means recompressing at a different level, or
//! with a different BGZF block size, does not invalidate the record: what is
//! being asserted is that the bytes plethora reads are the bytes upstream
//! published, which is the claim that actually matters.

use std::path::Path;

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// The manifest file, at the root of `data/`.
pub const MANIFEST: &str = "data/MANIFEST.toml";

#[derive(Debug, Deserialize, Serialize)]
pub struct Manifest {
    pub source: Source,
    #[serde(rename = "file")]
    pub files: Vec<Entry>,
}

/// Where the vendored copies were taken from.
#[derive(Debug, Deserialize, Serialize)]
pub struct Source {
    /// The upstream repository.
    pub repository: String,
    /// The commit the files were taken at, so the copy is pinned to a tree
    /// rather than to a branch that can move under it.
    pub commit: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Entry {
    /// The name upstream gives the file, which is also what the scripts expect.
    pub name: String,
    /// The path in `data/`, which for the large files carries a `.gz`.
    pub vendored: String,
    /// SHA-256 of the plaintext, not of the compressed copy.
    pub sha256: String,
    /// Plaintext size, as a second, cheaper check.
    pub bytes: u64,
    /// Line count, which is the number a human can sanity-check against
    /// upstream without downloading anything.
    pub lines: u64,
    /// What the file is for, since the names do not say.
    pub description: String,
}

impl Manifest {
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(MANIFEST);
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
    }

    pub fn store(&self, root: &Path) -> Result<()> {
        let path = root.join(MANIFEST);
        let body = toml::to_string_pretty(self)?;
        let text = format!(
            "# Generated by `cargo xtask fetch-data`. Do not edit by hand.\n\
             #\n\
             # `sha256` is of the plaintext each file decompresses to, so a\n\
             # recompression at another level still verifies. `cargo xtask\n\
             # check-data` re-reads every file and compares.\n\n{body}"
        );
        std::fs::write(&path, text).with_context(|| format!("writing {}", path.display()))?;
        Ok(())
    }
}

/// The three numbers a vendored file is checked against.
pub struct Digested {
    pub sha256: String,
    pub bytes: u64,
    pub lines: u64,
}

/// Digests a plaintext stream without holding it in memory: the domains BED is
/// 29 MB and there is no reason to buffer it.
pub fn digest(mut reader: impl std::io::Read) -> Result<Digested> {
    let mut hasher = Sha256::new();
    let mut bytes = 0u64;
    let mut lines = 0u64;
    let mut buffer = vec![0u8; 1 << 16];
    loop {
        let n = reader.read(&mut buffer)?;
        if n == 0 {
            break;
        }
        hasher.update(&buffer[..n]);
        bytes += n as u64;
        // A newline count over 46 MB, once, at vendoring time. bytecount would
        // be faster and is a dependency this does not need.
        #[allow(clippy::naive_bytecount)]
        {
            lines += buffer[..n].iter().filter(|&&b| b == b'\n').count() as u64;
        }
    }
    Ok(Digested {
        sha256: format!("{:x}", hasher.finalize()),
        bytes,
        lines,
    })
}

impl Entry {
    /// Compares a digest against what the manifest records, naming which of the
    /// three disagreed rather than only that something did.
    pub fn verify(&self, got: &Digested) -> Result<()> {
        if got.bytes != self.bytes {
            bail!(
                "{}: {} bytes, manifest says {}",
                self.name,
                got.bytes,
                self.bytes
            );
        }
        if got.lines != self.lines {
            bail!(
                "{}: {} lines, manifest says {}",
                self.name,
                got.lines,
                self.lines
            );
        }
        if got.sha256 != self.sha256 {
            bail!(
                "{}: sha256 {}, manifest says {}",
                self.name,
                got.sha256,
                self.sha256
            );
        }
        Ok(())
    }
}
